services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=my_db
      - POSTGRES_USER=postgres        
      - POSTGRES_PASSWORD=1234 
    ports:
      - "5432:5432"  
    volumes:
      - postgres_data:/var/lib/postgresql/data  

volumes:
  postgres_data:
    driver: local